// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAClPJNBTwkPwkM3YyBX5-zwfMuhYKibeY',
    appId: '1:578282277969:web:00c743b2f8174326e53c70',
    messagingSenderId: '578282277969',
    projectId: 'pmobpetakgov',
    authDomain: 'pmobpetakgov.firebaseapp.com',
    storageBucket: 'pmobpetakgov.appspot.com',
    measurementId: 'G-W4S2ZR0YQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp66QC6_nL7IqNg1jlHSNeNRp0If-RUrc',
    appId: '1:578282277969:android:b464b9313ad03ac7e53c70',
    messagingSenderId: '578282277969',
    projectId: 'pmobpetakgov',
    storageBucket: 'pmobpetakgov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy2jiKgFDtdTcpoEVTbck5NtUiybW2tZQ',
    appId: '1:578282277969:ios:b24f88dedca251c4e53c70',
    messagingSenderId: '578282277969',
    projectId: 'pmobpetakgov',
    storageBucket: 'pmobpetakgov.appspot.com',
    iosBundleId: 'com.example.pmobPetakgov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy2jiKgFDtdTcpoEVTbck5NtUiybW2tZQ',
    appId: '1:578282277969:ios:b24f88dedca251c4e53c70',
    messagingSenderId: '578282277969',
    projectId: 'pmobpetakgov',
    storageBucket: 'pmobpetakgov.appspot.com',
    iosBundleId: 'com.example.pmobPetakgov',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAClPJNBTwkPwkM3YyBX5-zwfMuhYKibeY',
    appId: '1:578282277969:web:cdbe9e46ca8a4a68e53c70',
    messagingSenderId: '578282277969',
    projectId: 'pmobpetakgov',
    authDomain: 'pmobpetakgov.firebaseapp.com',
    storageBucket: 'pmobpetakgov.appspot.com',
    measurementId: 'G-6BKYPV2K0L',
  );
}
